version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - db
    command: >
      sh -c "sleep 20 &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py loaddata /backend/stocks/fixtures/sp500.json &&
            gunicorn --config /web/gunicorn_config.py config.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./web:/web
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/project.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    networks:
      - app-network

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
